name: Poll Autofun

on:
  schedule:
    - cron:  '*/5 * * * *'   # every 5 minutes UTC
  workflow_dispatch:

jobs:
  hit-endpoint:
    runs-on: ubuntu-latest
    steps:
      - name: Call /api/cron
        run: |
          curl -X POST "https://terminalfun.vercel.app/api/cron" \
               --fail --silent --show-error
